# RTP Proxy Configuration

[server]
# gRPC server listen address
grpc_listen_address = "0.0.0.0"

# gRPC server listen port
grpc_listen_port = 50051

[logging]
# Enable file logging (if true, logs only to file; if false, logs to console)
file_enabled = true

# Log directory path
directory = "./logs"

# Log file name prefix
file_prefix = "rtpproxy"

# Maximum log file size in MB (default: 100)
max_file_size = 100

# Maximum number of log files to keep (default: 5)
max_log_files = 5
